import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/components/app-sidebar";
import {UserProvider} from "@/PROVIDER"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <UserProvider>
          <SidebarProvider>
            <AppSidebar /> {/* Now the sidebar can access the user's name */}
            <main className="w-full overflow-y-auto">
              <SidebarTrigger />
              {children} {/* All your pages can access the data too */}
            </main>
          </SidebarProvider>
        </UserProvider>
  )
}
